### PR TITLE
Remove global variables

### PR DESCRIPTION
**Pull request by Ajnasz**
Few variable was not defined using var and those were polluting the global namespace.

### CODE REVIEW

**Comment by BaseMax** [comment]
@Ajnasz  can you please update this extension? i really love this extension but its not working with FireFox latest version 32,and it looks like original developers already dropped this project.no update since 2011.

**Comment by Ajnasz** [comment]
Hey @hebrew878!

I would suggest to use the built in developer tools, there you can catch all headers.

**Comment by BaseMax** [comment]
i found no such option in FF. i can see all headers using FireBug
extension but i need the most important option REPLAY. Is there any
REPLAY option in FireBug or anywhere?

**Comment by Ajnasz** [comment]
On the network tab, you see the request, right clicking on it and you can edit and resend the request.
https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor#Edit_and_Resend

**Pull request closed without merging**
